VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes # Enable VIALRGB
EEPROM_DRIVER = custom
RAW_ENABLE = yes



QMK_SETTINGS = yes
MAGIC_ENABLE = yes
GRAVE_ESC_ENABLE = yes
TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes